### ISSUE TITLE
Input/output file breedte

### ISSUE THREAD

**Issue by PaulGoedhart** [jwkruisselbrink/vscode-genstat-extension#17]
Bij de aanroep van GenBatch kan de breedte van de invoer en uitvoer file ingesteld worden. Met name dat laatste is erg handig. Dat gaat als volgt:
genbatch "genfile"/200 "lisfile"/100 /d="directory"
Verzoek om een setting voor beiden.

**Comment by jwkruisselbrink** [comment]
Done
