### ISSUE TITLE
F11 help (zie mijn e-mail voor een suggestie hoe dit te doen)

### ISSUE THREAD

**Issue by PaulGoedhart** [jwkruisselbrink/vscode-genstat-extension#2]
Alleen de GenStat help file is momenteel geimplementeerd: 
  C:\Program Files\Gen19Ed\Doc\Genstat.chm
De Biometris help file is nog niet geimplementeerd:
  C:\Program Files\Gen19Ed\AddIns\Biometris-19ed.chm

Er zijn twee files met de GenStat/Biometris directives. Het zou heel mooi zijn als de file namen en directories van deze twee files in de settings aangepas kunnen worden (net als GenBatch.exe). Dan kan ik de files tzt (voor 20ed bijvoorbeeld) zelf aanpassen. Default locatie mag wat mij betreft zijn C:\ProgramData\GenStat\Gen19Ed\

**Comment by jwkruisselbrink** [comment]
Should be resolved in version 0.0.4
