### ISSUE TITLE
Genbatch return values

### ISSUE THREAD

**Issue by PaulGoedhart** [jwkruisselbrink/vscode-genstat-extension#20]
Warning in GenStat programma geeft return code 1
Fault in programma geeft return code 2
Messages moeten daar op aangepast worden
0 : GenStat run completed. Duration 00:00:00.0 (icon groen vinkje)
1 : GenStat run completed with warnings. Duration 00:00:00.0 (icon warning bijv. oranje uitroepteken)
2 : GenStat run completed with faults. Duration 00:00:00.0 (icon fault rood kruisje zoals nu)

De "Duration" mag van mij op tienden van seconden afgerond worden, met "leading zeroes".

**Comment by jwkruisselbrink** [comment]
Done!
