### ISSUE TITLE
Key voor snelle wissel van LIS file naar GEN file

### ISSUE THREAD

**Issue by PaulGoedhart** [jwkruisselbrink/vscode-genstat-extension#3]
De werkwijze is F12 vanuit .GEN geeft .LIS file. Maar vanuit die .LIS file wil ik snel naar de bijbehorende .GEN file. Zou heel fijn zijn als dat met een key zou kunnen. Bijvoorbeeld Alt-F12.
En Alt-F12 vanuit .GEN zou dan de bijbehorende .LIS kunnen geven!

**Comment by jwkruisselbrink** [comment]
Should be resolved in version 0.04
