### ISSUE TITLE
F12 functionaliteit voor R on top of existing R extension of Yuki Ueda (of een andere)

### ISSUE THREAD

**Issue by PaulGoedhart** [jwkruisselbrink/vscode-genstat-extension#8]
Uitvoer schrijven naar ".Rou" file. In CRiSP heb ik deze functionaliteit ook via een BAT file met
set Rprogram="c:\Program Files\r\R-3.5.0\bin\x64\Rterm.exe"
set Roptions=--no-restore --no-save --silent --args
%Rprogram% %Roptions% "%1" < "%1.R" > "%1.rou" 2>&1

Hierin is %1 de surname van het R programma. Misschien moet er nog wat gedaan worden aan de working directory!
Tevens Ctrl-F12 functionaliteit om snel te switchen tussen de R file en de Rou file (net zoals ik voorgesteld heb voor GenStat). En commentaar kleuren in de Rou file.

**Comment by PaulGoedhart** [comment]
Onderstaande BAT file roept R aan en schrijft de uitvoer weg naar een .Rou file. Het laat zien hoe de working directory in R gespecificeerd kan worden. In R kan met getwd() gecontroleerd worden of deze inderdaad goed staat. In CRiSP gebruikte ik een aanroep vanuit WinBatch om de working directory te specificeren.

@echo off
rem Runs an R script and send output to an .Rou file in the same directory.
rem First parameter is the full path to the R script file.
rem The working directory in R can be set to the path of the R script by two methods:
rem 1. Set an environmental variable in this batfile by means of 
rem      set R_SETWD=%~dp1
rem    then set the working directory in the R script as follows
rem      if (Sys.getenv('R_SETWD') != "") setwd(Sys.getenv('R_SETWD'))
rem    This method is used below by creating a local .Profile file in which 
rem    the working directory is changed at start-up.
rem 3. Change the directory in this batfile by means of
rem       cd "%~dp1"
rem    This does not require an environmental variable or a .Profile file
rem
rem This is an alternative way of running R
rem %Rprogram% %Roptions% "%~nx1" < "%~dpnx1" > "%~dpn1.Rou" 2>&1
rem ==== Prepare
set R_SETWD=%~dp1
set Rprogram="c:\Program Files\r\R-3.5.0\bin\x64\R.exe"
set Roptions=--no-save --no-restore --silent --no-timing
@echo setwd(Sys.getenv('R_SETWD')) > .Rprofile
rem ==== Call R
%Rprogram% CMD BATCH %Roptions% "%~dpnx1" "%~dpn1.Rou"
rem ==== Clean-up
set R_SETWD=
set Rprogram=
set Roptions=
if exist .Rprofile del .Rprofile

**Comment by jwkruisselbrink** [comment]
Won't fix in this extension. Created a separate vsrrunner extension for this.
